version: '3.9'

services:
  client:
    image: grpc-python-client:latest
    build: 
      context: .
      dockerfile: .Dockerfile
    platform: linux/amd64
    volumes:
      - ./src:/src/app
      - ../protos:/src/protos
      - venv:/src/app/.venv
      - vscode-server:/root/.vscode-server
    networks:
      - grpc

volumes:
  venv:
  vscode-server: