# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simple.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csimple.proto\x12\rsimplePackage\"?\n\x0eRequestMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08sentFrom\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"t\n\x0cReplyMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08sentFrom\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x35\n\x0erequestMessage\x18\x04 \x01(\x0b\x32\x1d.simplePackage.RequestMessage2\xdb\x02\n\rSimpleMessage\x12J\n\x0cSimple_Unary\x12\x1d.simplePackage.RequestMessage\x1a\x1b.simplePackage.ReplyMessage\x12S\n\x13Simple_ServerStream\x12\x1d.simplePackage.RequestMessage\x1a\x1b.simplePackage.ReplyMessage0\x01\x12S\n\x13Simple_ClientStream\x12\x1d.simplePackage.RequestMessage\x1a\x1b.simplePackage.ReplyMessage(\x01\x12T\n\x12Simple_BiDirection\x12\x1d.simplePackage.RequestMessage\x1a\x1b.simplePackage.ReplyMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'simple_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUESTMESSAGE']._serialized_start=31
  _globals['_REQUESTMESSAGE']._serialized_end=94
  _globals['_REPLYMESSAGE']._serialized_start=96
  _globals['_REPLYMESSAGE']._serialized_end=212
  _globals['_SIMPLEMESSAGE']._serialized_start=215
  _globals['_SIMPLEMESSAGE']._serialized_end=562
# @@protoc_insertion_point(module_scope)
