# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import simple_pb2 as simple__pb2


class SimpleMessageStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Simple_Unary = channel.unary_unary(
                '/simplePackage.SimpleMessage/Simple_Unary',
                request_serializer=simple__pb2.RequestMessage.SerializeToString,
                response_deserializer=simple__pb2.ReplyMessage.FromString,
                )
        self.Simple_ServerStream = channel.unary_stream(
                '/simplePackage.SimpleMessage/Simple_ServerStream',
                request_serializer=simple__pb2.RequestMessage.SerializeToString,
                response_deserializer=simple__pb2.ReplyMessage.FromString,
                )
        self.Simple_ClientStream = channel.stream_unary(
                '/simplePackage.SimpleMessage/Simple_ClientStream',
                request_serializer=simple__pb2.RequestMessage.SerializeToString,
                response_deserializer=simple__pb2.ReplyMessage.FromString,
                )
        self.Simple_BiDirection = channel.stream_stream(
                '/simplePackage.SimpleMessage/Simple_BiDirection',
                request_serializer=simple__pb2.RequestMessage.SerializeToString,
                response_deserializer=simple__pb2.ReplyMessage.FromString,
                )


class SimpleMessageServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Simple_Unary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Simple_ServerStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Simple_ClientStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Simple_BiDirection(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimpleMessageServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Simple_Unary': grpc.unary_unary_rpc_method_handler(
                    servicer.Simple_Unary,
                    request_deserializer=simple__pb2.RequestMessage.FromString,
                    response_serializer=simple__pb2.ReplyMessage.SerializeToString,
            ),
            'Simple_ServerStream': grpc.unary_stream_rpc_method_handler(
                    servicer.Simple_ServerStream,
                    request_deserializer=simple__pb2.RequestMessage.FromString,
                    response_serializer=simple__pb2.ReplyMessage.SerializeToString,
            ),
            'Simple_ClientStream': grpc.stream_unary_rpc_method_handler(
                    servicer.Simple_ClientStream,
                    request_deserializer=simple__pb2.RequestMessage.FromString,
                    response_serializer=simple__pb2.ReplyMessage.SerializeToString,
            ),
            'Simple_BiDirection': grpc.stream_stream_rpc_method_handler(
                    servicer.Simple_BiDirection,
                    request_deserializer=simple__pb2.RequestMessage.FromString,
                    response_serializer=simple__pb2.ReplyMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'simplePackage.SimpleMessage', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SimpleMessage(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Simple_Unary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simplePackage.SimpleMessage/Simple_Unary',
            simple__pb2.RequestMessage.SerializeToString,
            simple__pb2.ReplyMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Simple_ServerStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/simplePackage.SimpleMessage/Simple_ServerStream',
            simple__pb2.RequestMessage.SerializeToString,
            simple__pb2.ReplyMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Simple_ClientStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/simplePackage.SimpleMessage/Simple_ClientStream',
            simple__pb2.RequestMessage.SerializeToString,
            simple__pb2.ReplyMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Simple_BiDirection(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/simplePackage.SimpleMessage/Simple_BiDirection',
            simple__pb2.RequestMessage.SerializeToString,
            simple__pb2.ReplyMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
